spring:
  datasource:
    password: osf77
    url: jdbc:postgresql://localhost/gestao?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:db/migration 
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html; charset=utf-8
    cache: false
    prefix: classpath:/templates/