spring:
  datasource:
    password: osf77
    url: jdbc:postgresql://localhost/gestao?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:db/migration 